; Laboratoire 6 — même transport que labos 1-5

[env:esp32_wifi_tcp]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DCOMM_WIFI
lib_deps =
    bblanchon/ArduinoJson@^7.3.1
    pololu/VL53L0X@^1.3.1

; [env:esp32_wifi_mqtt]
; platform = espressif32
; board = esp32dev
; framework = arduino
; build_flags = -DCOMM_WIFI -DCOMM_WIFI_MQTT
; lib_deps =
;     bblanchon/ArduinoJson@^7.3.1
;     knolleary/PubSubClient@^2.8
;     pololu/VL53L0X@^1.3.1

; [env:esp32_bt]
; platform = espressif32
; board = esp32dev
; framework = arduino
; build_flags = -DCOMM_BT
; lib_deps =
;     bblanchon/ArduinoJson@^7.3.1
;     pololu/VL53L0X@^1.3.1
